### ISSUE TITLE
ssh connections get corrupted

### ISSUE THREAD

**Issue by gflarity** [pghalliday/tls-tunnel#1]
Hi,

Looks very promising but I tried using this with SSH and it doesn't work. If you run ssh with the -v option you'll see that it either stalls completely or something get's corrupted. I suspect the some bytes are getting lost.

I should add that I'm using the version from npm.

Cheers,
GF

**Comment by pghalliday** [comment]
I think this will be because some of the packets get merged or broken up in a way that SSH doesn't like. It might be addressed in https://github.com/pghalliday/single-tls-tunnel. At some point I mean to update tls-tunnel to use single-tls-tunnel internally but if you only have a simple use case then you may want to try using it directly (no guarantees, i haven't tried it with SSH - works with TLS though)

**Comment by pghalliday** [comment]
version 1.0.0 now depends on single-tls-tunnel so hopefully this issue is fixed - now figuring out how to create an automated test for it

**Comment by pghalliday** [comment]
an automated test is still escaping me but i just verified that i can connect using SSH with 1.0.0

**Comment by pghalliday** [comment]
Added a manual test

**Comment by gflarity** [comment]
Thanks!
